[build]
  publish = "prl/prlfridge" # Specify the directory where your build output is located
  command = "npm run build" # The build command to run

[[redirects]] # Optional: Configure redirects for client-side routing
  from = "/*"
  to = "/views/index.html"
  status = 200

[[headers]] # Optional: Configure headers (e.g., for caching)
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[context.production.environment] # Optional: Set environment variables for production
  NODE_ENV = "production"

[context.deploy-preview.environment] # Optional: Set environment variables for deploy previews
  NODE_ENV = "development"



